kalk/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView



urlpatterns = [
    url(r'^admin/', admin.site.urls), 
    url(r'^popisi/', include('popisi.urls')),
    url(r'^$', RedirectView.as_view(url='/popisi/', permanent=False)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

popisi/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^postavke/$', views.PostavkaListView.as_view(), name='postavke'),
    url(r'^postavka/(?P<pk>\d+)$', views.PostavkaDetailView.as_view(), name='postavka-detail'),
    url(r'^specifikacije/$', views.SpecifikacijaListView.as_view(), name='specifikacije'),
    url(r'^specifikacija/(?P<pk>\d+)$', views.SpecifikacijaDetailView.as_view(), name='specifikacija-detail'),
    url(r'^popisne_postavke/$', views.PopisnaPostavkaListView.as_view(), name='popisne_postavke'),
    url(r'^popisna_postavka/(?P<pk>\d+)$', views.PopisnaPostavkaDetailView.as_view(), name='popisna_postavka-detail'),
    url(r'^popisi/$', views.PopisListView.as_view(), name='popisi'),
    url(r'^popis/(?P<pk>\d+)$', views.PopisDetailView.as_view(), name='popis-detail'),
    


    url(r'^ime/$', views.get_ime, name='ime'),

    url(r'^im/$', views.im, name='im'),
    
    url(r'^vaja/$', views.vaja, name='vaja'),
    
    url(r'^popisna_postavka/nova/$', views.popisna_postavka_nova, name='popisna_postavka-nova'),
    
]

popisi/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


    

class Projekt(models.Model):
    naziv_projekta = models.CharField(max_length=200, default ="naziv projekta",null=True)
    opis_projekta = models.TextField(max_length=2000,default="opis projekta ")
    datum_projekta = models.DateField()
    uporabnik = models.ForeignKey(User, null=True, blank=True)
    class Meta: 
        ordering = ['-datum_projekta']
    def __str__(self):
        return self.naziv_projekta
    def get_absolute_url(self):
        return reverse('projekt-detail', args=[str(self.id)]) 

class Podrocje(models.Model):
    koda_podrocja = models.CharField(max_length=50,null=True)
    naziv_podrocja = models.CharField(max_length=50, default ="industrijski_objekti")
    splosna_dolocila_podrocja = models.TextField(max_length=2000,default="splošna določila področja industrijske gradnje")
    class Meta: 
        ordering = ["koda_podrocja"]
    def __str__(self):
        return self.naziv_podrocja  
    def get_absolute_url(self):
        return reverse('podrocje-detail', args=[str(self.id)]) 
 
class Zvrst(models.Model):
    zaporedna_stevilka_zvrsti = models.IntegerField(null=True)
    koda_zvrsti = models.CharField(max_length=50,null=True)
    naziv_zvrsti = models.CharField(verbose_name='Naziv zvrsti',max_length=50,default='GRADBENA DELA')        
    splosna_dolocila_zvrsti = models.TextField(max_length=2000,default="splošna določila zvrsti GRADBENA DELA ")
    class Meta: 
        ordering = ["zaporedna_stevilka_zvrsti"]
    def __str__(self):
        #return self.naziv_zvrsti
        return '%s, %s, %s' % (self.zaporedna_stevilka_zvrsti, self.koda_zvrsti, self.naziv_zvrsti) 
    def get_absolute_url(self):
        return reverse('zvrst-detail', args=[str(self.id)]) 

class Skupina(models.Model):
    zaporedna_stevilka_skupine = models.IntegerField(null=True)
    koda_skupine = models.CharField(max_length=50,null=True)
    naziv_skupine = models.CharField(verbose_name='Naziv skupine',max_length=50,default='Zemeljska dela')
    splosna_dolocila_skupine = models.TextField(max_length=2000,default="splošna določila skupine ZEMELJSKA DELA ")
    zvrst = models.ForeignKey('Zvrst',on_delete=models.CASCADE)    
     
    class Meta:  
        ordering = ["zaporedna_stevilka_skupine"]
    def __str__(self):
    #    return self.naziv_skupine
        return '%s, %s, %s' % (self.zaporedna_stevilka_skupine, self.koda_skupine, self.naziv_skupine) 
    def get_absolute_url(self): 
        return reverse('skupina-detail', args=[str(self.id)]) 

class Dela(models.Model):
    zaporedna_stevilka_del = models.IntegerField(null=True) 
    koda_del = models.CharField(max_length=50,null=True)
    opis_del=models.CharField(verbose_name='Opis del',max_length=50)
    splosna_dolocila_del = models.TextField(max_length=2000,default="splošna določila za dela IZKOPI ")
    skupina = models.ForeignKey('Skupina', on_delete=models.CASCADE) 
    podrocje = models.ManyToManyField(Podrocje, default=[1,2,3,4])
    class Meta: 
        ordering = ["zaporedna_stevilka_del"]
    def __str__(self):
        return self.opis_del
        return '%s, %s, %s' % (self.zaporedna_stevilka_del, self.koda_del, self.opis_del)
    def get_absolute_url(self):
        return reverse('dela-detail', args=[str(self.id)]) 


class SkupinaSpecifikacijePostavke(models.Model):
    zaporedna_stevilka_skupine_specifikacije = models.IntegerField(null=True) 
    koda_skupine_specifikacije = models.CharField(max_length=50,null=True)
    opis_skupine_specifikacije=models.CharField(verbose_name='Opis skupine specifikacije',max_length=50)
    splosna_dolocila_skupine_specifikacije = models.TextField(max_length=2000,default="splošna določila za skupino specifikacije npr. kategorije zemljišča ")
    dela = models.ManyToManyField(Dela)
    

    class Meta: 
        ordering = ["zaporedna_stevilka_skupine_specifikacije"]
    def __str__(self):
        return self.opis_skupine_specifikacije
        return '%s, %s, %s' % (self.zaporedna_stevilka_skupine_specifikacije, self.koda_skupine_specifikacije, self.opis_skupine_specifikacije)
    def get_absolute_url(self):
        return reverse('skupinaspecifikacije-detail', args=[str(self.id)])

# primer Managerja
class SpecifikacijaManager(models.Manager):
    def get_queryset(self):
        return super(SpecifikacijaManager, self).get_queryset().filter(skupinaspecifikacije=1)

class SpecifikacijaPostavke(models.Model):
    zaporedna_stevilka_specifikacije = models.IntegerField(null=True)
    koda_specifikacije = models.CharField(max_length=50,null=True)    
    vsebina_specifikacije = models.CharField(verbose_name='standardna vsebina specifikacije postavke',max_length=100)
    splosna_dolocila_specifikacije = models.TextField(max_length=2000,default="splošna določila specifikacije")
    info = models.TextField(max_length=2000,default="tehnične informacije")
    skupinaspecifikacije = models.ForeignKey('SkupinaSpecifikacijePostavke',on_delete=models.CASCADE,null=True) 
    

    objects = models.Manager() # The default manager.
    specifikacija_objects = SpecifikacijaManager() # The Dahl-specific manager.


    class Meta: 
        ordering = ["zaporedna_stevilka_specifikacije"]
    def __str__(self):
        #return self.vsebina_specifikacije
        return ' %s, %s' % (self.koda_specifikacije,self.vsebina_specifikacije) 
    #    return self.vsebina_specifikacije
    def get_absolute_url(self):
        return reverse('specifikacija-detail', args=[str(self.id)]) 


class Postavka(models.Model): 
    zaporedna_stevilka_postavke = models.IntegerField(null=True)
    koda_postavke = models.CharField(max_length=100,null=True)
    opis_postavke = models.CharField(max_length=100)
    enota_mere = models.CharField(max_length=10)
    dela = models.ForeignKey('Dela', on_delete=models.SET_NULL, null=True)
    skupina_specifikacije_postavke = models.ManyToManyField(SkupinaSpecifikacijePostavke)
    splosna_dolocila_postavke = models.TextField(max_length=1000, default="splošna določila postavke")
    class Meta: 
        ordering = ["zaporedna_stevilka_postavke"]
    def __str__(self):
        return '%s, %s, %s, %s' % (self.zaporedna_stevilka_postavke,self.koda_postavke,self.opis_postavke, self.enota_mere)
    def get_absolute_url(self):
        return reverse('postavka-detail', args=[str(self.id)])    


class Popis(models.Model):
    naslov_popisa = models.CharField(max_length=50,null=True)
    naziv_objekta = models.CharField(max_length=50,null=True)
    opis_objekta = models.TextField(max_length=2000,default="opis objekta ")
    neto_povrsina_objekta=models.DecimalField(max_digits=20,decimal_places=2,default=('0.00'))
    podrocje = models.ForeignKey('Podrocje',on_delete=models.CASCADE,default=1)
    projekt = models.ForeignKey('Projekt',on_delete=models.CASCADE)
    class Meta: 
        ordering = ["naziv_objekta"]
    def __str__(self):
        return self.naziv_objekta
    def get_absolute_url(self):
        return reverse('popis-detail', args=[str(self.id)]) 

class PopisnaPostavka(models.Model): 
    koda_popisne_postavke= models.CharField(max_length=100,null=True)
    zaporedna_stevilka_popisne_postavke = models.IntegerField(null=True)
    postavka = models.ForeignKey('Postavka')
    specifikacija = models.ManyToManyField(SpecifikacijaPostavke,verbose_name='standardne specifikacije postavke')     
    specifikacija_uporabnika = models.TextField(max_length=2000,verbose_name='dodatne specifikacije postavke',null=True )
    popis = models.ForeignKey('Popis',on_delete=models.CASCADE, default=1)
    class Meta: 
        ordering = ["zaporedna_stevilka_popisne_postavke"]
    def __str__(self):
        return '%s, %s, %s' % (self.zaporedna_stevilka_popisne_postavke, self.koda_popisne_postavke, self.specifikacija,)
    def get_absolute_url(self):
        return reverse('popisna_postavka-detail', args=[str(self.id)])    




class Ime(models.Model):
    tvoje_ime = models.CharField(max_length=200)
    postavka = models.ManyToManyField(Postavka)     
    #specifikacija = models.ManyToManyField(Postavka)     

    def __str__(self):
        return self.tvoje_ime


################FUNKCIJEFUNKCIJEFUNKCIJE##############################################################################

popisi/forms.py
from django import forms
from .models import Ime

class ImeForm(forms.ModelForm):
    

    def __init__(self, *args, **kwargs):
        super(ImeForm, self).__init__(*args, **kwargs)
        
        


    class Meta:
        model = Ime
        fields = ('tvoje_ime',)
 #       widgets = {
 #       	'tvoje_ime': forms.CheckboxSelectMultiple
 #       }





data={'koda_popisne_postavke':'oh','zaporedna_stevilka_popisne_postavke':20,'postavka':4,'specifikacija':[8,9,10],'specifikacija_uporabnika':'hojladri','popis':2}


from .models import PopisnaPostavka,SpecifikacijaPostavke,Postavka,SkupinaSpecifikacijePostavke

class PopisnaPostavkaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PopisnaPostavkaForm, self).__init__(*args, **kwargs)
        
    

        self.fields['specifikacija'].queryset = SpecifikacijaPostavke.objects.all()
        self.fields['specifikacija'].label_from_instance = lambda obj: "%s" % (obj.koda_specifikacije)

        
        
#        self.fields['postavka'].queryset = Postavka.objects.all() 
 #       [postavka for postavka in self.fields['postavka'].queryset]
  #      print(postavka)    

   #     self.fields['postavka'].label_from_instance = lambda obj: "%s" % (obj.skupina_specifikacije_postavke)

    class Meta:
        model = PopisnaPostavka
        fields = ('zaporedna_stevilka_popisne_postavke','specifikacija','postavka','specifikacija_uporabnika','popis',)
        widgets = {
    #    	'postavka': forms.CheckboxSelectMultiple
            'specifikacija': forms.CheckboxSelectMultiple            
        }
        


popisi/views.py
from django.shortcuts import render
from django.views import generic
from popisi.models import Postavka,SpecifikacijaPostavke,Dela,Skupina,SkupinaSpecifikacijePostavke,PopisnaPostavka,Popis,SpecifikacijaManager
from django.db.models import Count

##################################################################


#exec(open("./popisi/views.py").read())

def stetje(): 
    print('dela')
    zap_st = 1
    for b in PopisnaPostavka.objects.all():
        b.zaporedna_stevilka_popisne_postavke = zap_st
        b.save()
        zap_st = zap_st + 1
stetje()

def skupaj():
    
    for a in PopisnaPostavka.objects.all():
        zdruzeno = '.'.join([a.postavka.koda_postavke]+[str(b.koda_specifikacije) for b in a.specifikacija.all()])
        a.koda_popisne_postavke=zdruzeno
        a.save() 
        print(a.koda_popisne_postavke)
skupaj()


def popisnapostavka():
    for a in Postavka.objects.all():
        print(a.skupina_specifikacije_postavke)
popisnapostavka()








#def koda_postavke():
#    for a in Postavka.objects.all():
#        print(a.dela.koda_del)
#koda_postavke()


#deluje ???
#def kodapopisa():
#	c = ""
#	for a in Popis.objects.all():
#		for b in a.specifikacija.all():
#			c+=b.koda_specifikacije
#	a.koda_popisne_postavke = c
#	a.save()
#kodapopisa()





# ta deluje odlično
#def list_zdruzevanje():
#    for a in Popis.objects.all():
#        zdruzeno = '.'.join([str(b.koda_specifikacije) for b in a.specifikacija.all()])
#        a.koda_popisne_postavke=zdruzeno
#        a.save()
#list_zdruzevanje()

#tudi ta deluje , le da je za postavko
#def list_zdruzevanje1():
#    for c in Popis.objects.all():
#        c.koda_popisne_postavke=c.postavka.koda_postavke
#        c.save()
#        print(c.koda_popisne_postavke) 
#list_zdruzevanje1()







# ta funkcija združuje list  "".join(['miha','el'])  v mihael



#class ZeroObject(object):
#    def __add__(self, other):
#    return other

#>>> sum(["hi", "there"], ZeroObject())
#'hithere'







#############################################################

from django.http import HttpResponseRedirect
from django.http import HttpResponse
from popisi.models import Ime
from .forms import ImeForm

def im(request):
    
    if request.method == 'POST':

        form=ImeForm(request.POST)
        return HttpResponse('<tr><th><label for="id_tvoje_ime">Tvoje ime:</label></th><td><input type="text" name="tvoje_ime" maxlength="200" required id="id_tvoje_ime" /></td></tr>'
)

#    else:
#        form = ImeForm()
#    return render(request,'popisi/ime.html',{'form':form})
def get_ime(request):

    if request.method == 'POST':
        form = ImeForm(request.POST) 
       

        if form.is_valid():
            #form.save()
            #print (request.COOKIES)
            #print (request.GET.lists())
            #print (request.body)
            a=request.POST['tvoje_ime']
            print(a)
            
            
            
            b=Postavka.objects.get(koda_postavke=a)
            for b in b.skupina_specifikacije_postavke.all():

                print(b.specifikacijapostavke_set
                     .all())





            #b=Ime.objects.get(tvoje_ime=a)
            #print(b)

            

            #print (request.GET.get('tvoje_ime'))
            #print (request.path_info)
            #print (request.encoding)
            #print (request.content_type)
            return HttpResponse('sonček je  ')
    else:
        form = ImeForm()
        print(form)
    return render(request, 'popisi/ime.html', {'form': form})
    





from .forms import PopisnaPostavkaForm

def popisna_postavka_nova(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PopisnaPostavkaForm(request.POST)
        # check whether it's valid:
        if form.is_valid(): 
            form.save()# process the data in form.cleaned_data as required 
            # ... 
            # redirect to a new URL: 

            return HttpResponseRedirect('/popisi/popisne_postavke/')
    # if a GET (or any other method) we'll create a blank form 
    else: form = PopisnaPostavkaForm()
    return render(request, 'popisi/popisna_postavka_nova.html', {'form': form})





from django.http import HttpResponse

def vaja(request):
    a=request.path
    return HttpResponse(a)


















def index(request):
    
    stej_postavke=Postavka.objects.all().count()
    stej_popisne_postavke=PopisnaPostavka.objects.all().count()
    q = PopisnaPostavka.objects.annotate(Count('postavka'))

    return render(
        request,
        'index.html',
        context={'stej_postavke':stej_postavke,'stej_popisne_postavke':stej_popisne_postavke,'q':q},
    )
class PostavkaListView(generic.ListView):
    model = Postavka
   # def get_queryset(self):
    #    return Postavka.objects.filter(opis_postavke__icontains='p')

class PostavkaDetailView(generic.DetailView):
    model = Postavka

class SpecifikacijaListView(generic.ListView):
    model = SpecifikacijaPostavke
#    def get_queryset(self):
 
#        return SpecifikacijaPostavke.objects.filter(skupinaspecifikacije__opis_skupine_specifikacije='odpornost proti obrabi površine')

class SpecifikacijaDetailView(generic.DetailView):
    model = SpecifikacijaPostavke

class PopisnaPostavkaListView(generic.ListView):
   
    model = PopisnaPostavka
   # def get_queryset(self):
    #    return Postavka.objects.filter(opis_postavke__icontains='p')
    #stetje()
class PopisnaPostavkaDetailView(generic.DetailView):
    model = PopisnaPostavka    

class PopisListView(generic.ListView):
   
    model = Popis
   # def get_queryset(self):
    #    return Postavka.objects.filter(opis_postavke__icontains='p')
    #stetje()
class PopisDetailView(generic.DetailView):
    model = Popis

#xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

popisi/templates/popisi/iiiime.html
<form action="" method="post">
    {% csrf_token %} 
    {{ form }}
    <input type="submit" value="Submit" />
</form>

popisi/templates/popisi/ime.html
<form action="" method="post">
    {% csrf_token %} 
    {{ form }}
    <input type="submit" value="Submit" />
</form>

popisi/templates/popisi/popis_detail.html



{% extends "base_generic.html" %}


{% block content %}

<STYLE>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
</STYLE>


<div style="background-color:black;color:white;padding:20px;">    

<!--{% for a in popis.popisnapostavka_set.all %}{{a.postavka.dela.skupinaspecifikacijepostavke_set.all}}{% endfor %}-->

{{a.postavka.dela.skupinaspecifikacijepostavke_set.all}}




  
  <p><strong>Projekt:</strong> <a href="">{{ popis.projekt.naziv_projekta }}</a></p>
  <p title="To je komentar za ta stavek "><strong>Objekt:</strong> {{ popis.naziv_objekta }}</p>
</div>  
  <table class="table table-bordered">
  <table class="table table-striped">

  <tr style="background-color:red;">
    <td>poz.</td>
    <td>šifra/opis postavke</td>
    <td>em</td>
    <td>količina</td>
    <td>cena/em</td>
    <td>skupaj</td>
  </tr>

  {% for a in popis.popisnapostavka_set.all %}
  <tr>
    <td style ="font-size:100%;width:4%;"">{{a.zaporedna_stevilka_popisne_postavke}}</td>
    <td style="font-size:100%;width:40%;"><a href="{{ a.get_absolute_url }}">{{a.koda_popisne_postavke}}</a>
    <p style="font-size:100%;width:80%;background-color:#e0ebeb;">{{a.postavka.opis_postavke}} {% for b in a.specifikacija.all %} {{b.vsebina_specifikacije}} {% endfor %}{{a.specifikacija_uporabnika}}</p></td>
    <td style="font-size:100%;width:5%;background-color:#e0ebeb;">{{a.postavka.enota_mere}}</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  
  {% endfor %} 
  </table>

{% endblock %}


popisi/templates/popisi/popis_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Popisi </h1>
                  


    {% if popis_list %}
    <ul>

      {% for b in popis_list %}
      <li>
        <a href="{{ b.get_absolute_url }}">{{ b.projekt.naziv_projekta}},   {{b.naziv_objekta}},</a> 
                     
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Na žalost , nii popisa.</p>
    {% endif %}       
{% endblock %}


popisi/templates/popisi/popisna_postavka_nova.html

{% extends 'base_generic.html' %}





{% block content %}


<form action="" method="post">
    {% csrf_token %}
    {{ form.koda_popisne_postavke }}
    {{ form.zaporedna_stevilka_popisne_postavke }}
    {{ form.postavka }}
    
    {% for a in form.postavka %}{{a.skupina_specifikacije_postavke}}{% endfor %}
    
    {{ form.specifikacija_uporabnika }}
    {{ form.popis }}

    {{ form.specifikacija }}



    <input type="submit" value="Submit" />
</form>





{% endblock %}

popisi/templates/popisi/popisnapostavka_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Popis: {{ popisnapostavka.postavka }}</h1>

  <p><strong>Koda:</strong> <a href="">{{ popisnapostavka.koda_popisne_postavke }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Opis:</strong> {{ popisnapostavka.postavka }}</p>
  
  <p><strong>Specifikacija popisne postavke:</strong> {% for specifikacija in popisnapostavka.specifikacija.all %} {{specifikacija.koda_specifikacije}}, {{specifikacija.vsebina_specifikacije}}, {{specifikacija.splosna_dolocila_specifikacije}} {% endfor %} </p>

  <p><strong>Dodatna specifikacija:</strong> {{ popisnapostavka.specifikacija_uporabnika }}</p>


  <!--<p><strong>enota mere:</strong> {{ popis.enota_mere }}</p> 
  
  <p><strong>dela:</strong> {{ postavka.dela }}</p>  
  <p><strong>splošna določila postavke
  :</strong> {{ postavka.splosna_dolocila_postavke }}</p>

  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>  -->

{% endblock %}


popisi/templates/popisi/popisnapostavka_list.html

{% extends "base_generic.html" %}

{% block content %}
    <h1><p>Popisi del</p>
        <p>Objekt:</p> </h1>
                  
<STYLE>
p.test{
      width:25em;
      border:1px solid #000000;
      word-wrap:break-word;
}     

</STYLE>


{% if popisnapostavka_list %}

<div class="col-lg-6">
<table class="table table-bordered">

<thead>
<tr>
  <th>Zap.st</th>
  <th>Oznaka</th>
  <th>Opis</th>
  <th>Specifikacija uporabnika</th>
</tr>
</thead>

<tbody>
{% for b in popisnapostavka_list %}
<tr class="danger">
  <td>{{ b.zaporedna_stevilka_popisne_postavke}}</td>
  <td><a href="{{ b.get_absolute_url }}">{{b.koda_popisne_postavke}}</a></td>
  <td>{{ b.postavka.opis_postavke }}</td>
  <td>{{b.specifikacija_uporabnika}}</td>

</tr>
{% endfor %}

</tbody>


</table>

</div>

<div class="col-lg-6">
<table class="table table-bordered">

<thead>
<tr>
  <th>Zap.st</th>
  <th>Oznaka</th>
  <th>Opis</th>
  <th>Specifikacija uporabnika</th>
</tr>
</thead>

<tbody>
{% for b in popisnapostavka_list %}
<tr class="danger">
  <td>{{ b.zaporedna_stevilka_popisne_postavke}}</td>
  <td><a href="{{ b.get_absolute_url }}">{{b.koda_popisne_postavke}}</a></td>
  <td>{{ b.postavka.opis_postavke }}</td>
  <td>{{b.specifikacija_uporabnika}}</td>

</tr>
{% endfor %}

</tbody>


</table>

</div>



    {% endif %}

<!--     {% if popisnapostavka_list %}
    <ul>

      {% for b in popisnapostavka_list %}
      <li>
        <a href="{{ b.get_absolute_url }}">
        <p>{{ b.zaporedna_stevilka_popisne_postavke}},{{b.koda_popisne_postavke}},</p>
      <div>
        <p class='test'>{{ b.postavka.opis_postavke }}</a> 
       
        {% for a in b.specifikacija.all %} , {{a.vsebina_specifikacije}} {% endfor %}, {{b.specifikacija_uporabnika}}</p>
      </div>
      <p> {{b.postavka.enota_mere}}</p>


      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Na žalost , nii popisa.</p>
    {% endif %} -->       
{% endblock %}

popisi/templates/popisi/postavka_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Postavka: {{ postavka.opis_postavke }}</h1>

  <p><strong>Koda:</strong> <a href="">{{ postavka.koda_postavke }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Opis:</strong> {{ postavka.opis_postavke }}</p>
  
  
  <p><strong>enota mere:</strong> {{ postavka.enota_mere }}</p> 
  
  <p><strong>dela:</strong> {{ postavka.dela }}</p>  
  


  <p><strong>Specifikacije :</strong> <br>
  {% for a in postavka.dela.skupinaspecifikacijepostavke_set.all %}
  <b>{{ a.opis_skupine_specifikacije }}</b><br>
   {% for b in a.specifikacijapostavke_set.all %}
    - {{ b.vsebina_specifikacije }}<br>
    {% endfor %}
  {% endfor %}</p>   
  


  <p><strong>splošna določila postavke:</strong> {{ postavka.splosna_dolocila_postavke }}</p>

 

  <!--<p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <p><strong>Specifikacija postavke:</strong> {% for specifikacija in postavka.specifikacija.all %} {{specifikacija}} {% endfor %}</p>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>  -->

{% endblock %}
